version: "3.8"

services:
  frontend:
    build: ../../frontend
    ports:
      - "3000:3000"
    volumes: 
      - ../../frontend:/TODO
    environment:
      - REST_API_URL=http://localhost:5000
    
  backend:
    build: ../../backend
    ports:
      - "5000:5000"
    volumes:
      - "../../backend:/TODO"
    environment:
      - DATABASE_URL=postgres://user:password@db:5450/mystictuner

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mystictuner
    ports:
      - "5450:5432"
